# Generated by Django 2.1.7 on 2019-05-29 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outils', '0003_auto_20190529_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material_proto',
            name='density',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='material_support',
            name='density',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
