# Generated by Django 2.1.7 on 2019-06-03 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outils', '0004_auto_20190529_1805'),
    ]

    operations = [
        migrations.AddField(
            model_name='printer',
            name='layer_height_max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='printer',
            name='layer_height_min',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='result',
            name='layer_height_cost',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
