# Generated by Django 2.1.7 on 2019-06-14 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outils', '0008_printer_infill_label_suppo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='result',
            old_name='volume_prototype',
            new_name='volume_prototype_cost',
        ),
        migrations.RemoveField(
            model_name='result',
            name='printer_mate',
        ),
        migrations.AddField(
            model_name='printer',
            name='infill_dens_proto_emp',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='printer',
            name='infill_dens_proto_emp_label',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='printer',
            name='infill_dens_proto_ful',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='printer',
            name='infill_dens_proto_ful_label',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='printer',
            name='infill_dens_proto_med',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='printer',
            name='infill_dens_proto_med_label',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='result',
            name='dens_proto_cost',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='result',
            name='dens_proto_mate',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='result',
            name='volume_prototype_cost_label',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='result',
            name='volume_prototype_mate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='result',
            name='volume_prototype_mate_label',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='prototype',
            name='filling_proto',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
