# Generated by Django 2.1.7 on 2019-06-14 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outils', '0011_auto_20190614_1122'),
    ]

    operations = [
        migrations.AddField(
            model_name='printer',
            name='rotation_X',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='printer',
            name='rotation_Y',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='printer',
            name='rotation_Z',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
