# Generated by Django 2.1.7 on 2019-06-14 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outils', '0012_auto_20190614_1819'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='printer',
            name='rotation_X',
        ),
        migrations.RemoveField(
            model_name='printer',
            name='rotation_Y',
        ),
        migrations.RemoveField(
            model_name='printer',
            name='rotation_Z',
        ),
        migrations.AddField(
            model_name='result',
            name='rotation_X',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='result',
            name='rotation_Y',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='result',
            name='rotation_Z',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
