# Generated by Django 2.1.7 on 2019-07-24 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('outils', '0014_auto_20190705_1437'),
    ]

    operations = [
        migrations.CreateModel(
            name='Overhang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('angle', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Overhang_angle',
            },
        ),
        migrations.AddField(
            model_name='printer',
            name='overhang_angle_label',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='printer',
            name='overhang_angle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='outils.Overhang'),
        ),
    ]
