# Generated by Django 2.1.7 on 2019-07-24 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('outils', '0015_auto_20190724_1421'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='overhang',
            options={'verbose_name': 'Overhang angle'},
        ),
    ]
