# Generated by Django 2.1.7 on 2019-07-24 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outils', '0016_auto_20190724_1423'),
    ]

    operations = [
        migrations.RenameField(
            model_name='result',
            old_name='image',
            new_name='image_0',
        ),
        migrations.AddField(
            model_name='result',
            name='image_45',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='result',
            name='overhang_cost',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='result',
            name='overhang_mate',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
