# Generated by Django 2.1.7 on 2019-07-24 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outils', '0017_auto_20190724_1614'),
    ]

    operations = [
        migrations.AddField(
            model_name='result',
            name='strategy_cost',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='result',
            name='strategy_mate',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
