# Generated by Django 2.1.7 on 2019-07-24 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outils', '0018_auto_20190724_1721'),
    ]

    operations = [
        migrations.RenameField(
            model_name='result',
            old_name='rotation_X',
            new_name='rotation_0_X',
        ),
        migrations.RenameField(
            model_name='result',
            old_name='rotation_Y',
            new_name='rotation_0_Y',
        ),
        migrations.RenameField(
            model_name='result',
            old_name='rotation_Z',
            new_name='rotation_0_Z',
        ),
        migrations.AddField(
            model_name='result',
            name='rotation_45_X',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='result',
            name='rotation_45_Y',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='result',
            name='rotation_45_Z',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
